site_name: "100 Great Bitcoin Questions"

theme:
  name: material
  
  features:
    - navigation.instant
    - navigation.tracking
  
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        # icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        # icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
